services:                                     
  fastsend:                          
    image: easytier/easytier:v2.5.0
    container_name: ${CONTAINER_NAME}         
    network_mode: host                    
    entrypoint: /bin/sh -c "/usr/local/bin/easytier-web-embed --api-server-port ${PANEL_APP_PORT_HTTP} --api-host \"${API_HOST}\" --config-server-port ${CONFIG_SERVER_PORT} --config-server-protocol udp & /usr/local/bin/easytier-core -w udp://127.0.0.1:${CONFIG_SERVER_PORT}/${CONFIG_USER} --machine-id ${MACHINE_ID}"
    volumes:
      - ./data:/app
    environment:
      - TZ=${TIME_ZONE}                       # 时区设置
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun  # 挂载tun设备
    labels:                                   
      createdBy: "Apps"                       