services:                                     
  fastsend:                          
    image: easytier/easytier:v2.5.0
    container_name: ${CONTAINER_NAME}         
    network_mode: host                    
    command: -w ${API_HOST}/${CONFIG_USER} --machine-id ${MACHINE_ID}
    volumes:
      - ./data:/app
    environment:
      - TZ=${TIME_ZONE}                       # 时区设置
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun  # 挂载tun设备
    labels:                                   
      createdBy: "Apps"                       