services:
  1panel-apps:
    image: ${IMAGE}
    container_name: ${CONTAINER_NAME}
    networks:
      - 1panel-network
    ports:
      - "${PANEL_APP_PORT_HTTP}:内部端口"
    volumes:
      - "./data:${DATA_PATH_INTERNAL}"
    environment:
    # 环境参数按需修改 (Modify the environment parameters as required)
      - TZ=${TIME_ZONE}
    labels:  
      createdBy: "Apps"
networks:
  1panel-network:
    external: true
