services:
  dnsmgr:
    image: netcccyun/dnsmgr:latest
    container_name: ${CONTAINER_NAME}
    restart: always
    labels:
      createdBy: "Apps"
    ports:
      - "${PANEL_APP_PORT_HTTP}:80"
    volumes:
      - ./data/.env:/app/www/.env
    environment:
      - TZ=${TIME_ZONE}
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
